## Client Credentials

POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic client 511536EF-F270-4058-80CA-1C89C192F69A

scope=api1
&grant_type=client_credentials

## Authorisation Code

## Step 1: Request - https://tools.ietf.org/html/rfc6749#section-4.1.1

### Redirect (GET) the user like so:

GET http://localhost:5000/connect/authorize?client_id=mvc
&response_type=code
&scope=openid
&redirect_uri=http%3A%2F%2Flocalhost%3A5002/callback
&state=state-296bc9a0-a2a2-4a57-be1a-d0e2fd9bb601

### Or POST to it:

POST http://localhost:5000/connect/authorize
Content-Type: application/x-www-form-urlencoded

client_id=mvc
&response_type=code
&scope=openid
&redirect_uri=http%3A%2F%2Flocalhost%3A5002/callback
&state=state-296bc9a0-a2a2-4a57-be1a-d0e2fd9bb601

###

@code = aa90f52b1aeda6ba1286ee4d2cf3f736c88fb899cef9d8a02c5a6adb527e8e5e

POST http://localhost:5000/connect/token
accept: application/json
authorization: Basic mvc 49C1A7E1-0C79-4A89-A3D6-A37998FB86B0
content-type: application/x-www-form-urlencoded

grant_type=authorization_code
&redirect_uri=http%3A%2F%2Flocalhost%3A5002/callback
&code={{code}}

###
POST http://localhost:5000/connect/token
accept: application/json
authorization: Basic mvc 49C1A7E1-0C79-4A89-A3D6-A37998FB86B0
content-type: application/x-www-form-urlencoded

grant_type=authorization_code
&redirect_uri=http%3A%2F%2Flocalhost%3A5002/callback
&code=236fedb532efa72b03cd4079691d1bc08aa51bc101b87a5adb514f44bf5dfa08